version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Detecting OS...
      - cat /etc/os-release
      - echo Installing unzip and curl via dnf...
      - dnf install -y unzip curl
      - echo Installing AWS CLI...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version



  pre_build:
    commands:
      - echo Preparing the environment...

  build:
    commands:
      - echo Building WAR file...
      - mvn clean package
      - echo WAR file generated.

  post_build:
    commands:
      - echo Deploying WAR to Tomcat...
      - curl -v -u "$TOMCAT_USERNAME:$TOMCAT_PASSWORD" -T target/Ecomm.war "http://3.109.208.89:8080/manager/text/deploy?path=/Ecomm&update=true"
      - echo Uploading WAR to S3...
      - aws s3 cp target/Ecomm.war s3://$S3_BUCKET/Ecomm.war
      - echo ✅ Deployment and upload complete.

artifacts:
  files:
    - target/Ecomm.war
