name: Build and Push Docker Image

on:
  push:
    branches: [ master ]  # Trigger on push to main
  workflow_dispatch:     # Manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest  # GitHub-hosted runner with Docker pre-installed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Enable BuildKit
      run: echo '{"features":{"attestations": true}}' > /etc/buildkit/buildkitd.toml
 

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: sreekanth45k/myapp:latest
        provenance: true
        sbom: true
        attests: type=provenance
